#!/bin/zsh

function myprint(){
	print -P "$@%{$reset_color%}"
}

for ((i=0; i<=10000000;++i)); do
	./gen > t.in
	./main < t.in > main.out
	./brute < t.in > brute.out

	#tput civis
	if diff -w main.out brute.out > /dev/null; then
		print -Pn " %B[%F{green}OK%F{whie}]%b $i\r"
	else
		myprint "%B[%F{red}WA%F{white}]%b %i\r"

		myprint "%B- input:%b"
		if (( $(wc -c < t.in) > 150 )); then
			myprint "input too big"
		else
			cat t.in
		fi

		myprint "%B- expected output:%b"
		if (( $(wc -c < brute.out) > 150 )); then
			myprint "expected output too big"
		else
			cat brute.out
		fi

		myprint "%B- got output:%b"
		if (( $(wc -c < main.out) > 150 )); then
			myprint "output too big"
		else
			cat main.out
		fi
		
		#tput cvvis
		exit 0
	fi
done
